title: Jeffrey Dunn
logo: "/images/kathmandu_port.PNG?raw=true"
description: >
  From Data-Driven Program Management to Big Data-Driven Data Science
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
