title: Jeffrey Dunn
logo: "/images/kathmandu_port.PNG?raw=true"
description: >
  Analytics, Data Science, Programming
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-166770781-1 # your Google Analytics tracking ID here
